doc-warnings: yes
test-warnings: no
strictness: high
max-line-length: 110
autodetect: yes
ignore-paths:
    # Ignore code that's not in the delivered
    - doc
    - tests
    - samples
    # Ignore build files
    - coverage_fix.py
    - version.py
python-targets:
    - 3
pylint:
  run: false
mccabe:
  run: false
pep257:
  disable:
    - D102
    - D200
    - D203
    - D205
    - D212
    - D400
    - D401
    - D404
    - D415
